version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: digital-forge-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./knowledge_base/index:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
